### PR TITLE
Merge the init_script update-repos.sh into the the task script update-repos (fixes #267)

### LINKED ISSUE #267: Snapshot build (2022.01.15 ~ 2022.01.17) failed

### PR DESCRIPTION
**Pull request by Atry**
Snapshot build (2022.01.15 ~ 2022.01.17) were pending because the worker for `PublishBinaryPackages` terminated before the step task started, therefore the `TimeoutSeconds` setting for the AWS task does not count.

This PR moves the volume mounting to the task script, so that volume mounting failures in the task script can be handled.

### CODE REVIEW

File: aws/userdata/update-repos.sh [hunk 1]
```diff
@@ -26,6 +26,23 @@ export VERSION
...
 if [ -z "$DOCKER_ONLY" ]; then
+  INSTANCE_ID=$(curl --retry 5 http://169.254.169.254/latest/meta-data/instance-id)
+
+  # We keep a shared XFS volume as the source of truth to avoid having to
+  # redownload from S3 every day, which can take a *really* long time.
+  VOLUME_ID="vol-096d2c45d13d3a865"
+
+  # Note: We can use try_really_hard from worker.sh because this is source'd, not
+  # executed.
+  try_really_hard aws ec2 attach-volume \
```
Comment (fredemmott) [inline aws/userdata/update-repos.sh:37]: I think this needs to check if it's already mounted: it can be called multiple times on the same worker if we're building multiple versions at the same time, e.g. for security updates

Comment (Atry) [reply aws/userdata/update-repos.sh]: Added the mount test

**Review by fredemmott — APPROVED** [review]
